# Generated by Django 5.1.6 on 2025-02-14 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(2, 'Ruolo 2'), (3, 'Ruolo 3'), (4, 'Ruolo 4'), (5, 'Ruolo 5'), (6, 'Ruolo 6'), (7, 'Ruolo 7'), (8, 'Ruolo 8'), (9, 'Ruolo 9')])),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assigner.person')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assigner.week')),
            ],
        ),
    ]
