# Generated by Django 5.1.6 on 2025-02-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assigner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='role',
            field=models.IntegerField(choices=[(1, 'Ruolo 1'), (2, 'Ruolo 2'), (3, 'Ruolo 3'), (4, 'Ruolo 4'), (5, 'Ruolo 5')]),
        ),
    ]
